server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: redis-api
  profiles:
    active: default
  data:
    redis:
      host: localhost
      port: 6379
      # No password required for localhost

# Logging Configuration
logging:
  level:
    com.miempresa.redis: INFO
    org.springframework.web: INFO

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
