server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: redis-api
  profiles:
    active: default
  data:
    redis:
      host: localhost
      port: 6379
      # No password required for localhost

# Configuración de Redisson
redisson:
  connection-pool-size: 64
  connection-minimum-idle: 24
  lock-watchdog-timeout: 30000
  rate-limit:
    lock-timeout: 5000
    cache-ttl: 600

# Configuración de rate limiting por defecto
rate-limit:
  endpoints:
    "/api/health":
      max-requests: 5
      time-window-seconds: 60
      enabled: true
      lock-timeout: 5000

# Logging Configuration
logging:
  level:
    com.miempresa.redis: INFO
    org.springframework.web: INFO

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
